name: Feature Request
description: You request a new feature
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
