name: Help me!
description: If you need help using the engine.
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
      placeholder: "I don't know how to do pancakes and I need help with creating a robot that cooks pancakes for me."
    validations:
      required: true

  - type: dropdown
    id: modding
    attributes:
      label: "Are you modding a build from source or with Lua?"
      options:
        - Lua
        - Source
        - I added a new system
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows x64"
        - "Windows x32"
        - "Windows x86"
        - "Linux"
        - "Mac"
        - "HTML5/Browser"
        - "Flash/Air-based target"
        - "Neko, HashLink, or other build system"
        - "Im talking about a GLOBAL help"
      multiple: true
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: false

  - type: textarea
    id: codeleak
    attributes:
      label: "Can you show the code? Only in case that you want"
      placeholder: "Code here, come on don't be shy! This helps for anyone to see if you have errors and that"
      render: |
        lua
        hx
        udkdodnsisdnduenejsjsd
      value: |
        lua:

        haxe:

        other:

    validations:
      required: false
