name: Question
description: Ask about something here.
labels: [question]
body:
  - type: textarea
    attributes:
      label: What is your question?
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: "It is a question of LUA or source"
      options:
        - Lua
        - Source
        - type: input
          attributes:
            placeholder: "Bro, its only a question"
          validations:
            required: false
    validations:
      required: true
