# This is a basic workflow to help you get started with Actions

name: Normal Build
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib git flixel https://github.com/HaxeFlixel/flixel/tree/4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxcpp https://github.com/Sirox228/hxcpp
          haxelib list
          haxelib install refactor
          haxelib run refactor replace source *.hx "/import vlc.MP4Handler;/import hxcodec.VideoHandler;\nimport hxcodec.VideoSprite;/"
          haxelib run refactor replace source *.hx "/MP4Handler/VideoSprite/"
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: linux
          path: "export/release/linux/bin"
          retention-days: 5
  Windows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib git flixel https://github.com/HaxeFlixel/flixel/tree/4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript 
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxcpp https://github.com/Sirox228/hxcpp
          haxelib list
          haxelib install refactor
          haxelib run refactor replace source *.hx "/import vlc.MP4Handler;/import hxcodec.VideoHandler;\nimport hxcodec.VideoSprite;/"
          haxelib run refactor replace source *.hx "/MP4Handler/VideoSprite/"
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windows
          path: export/release/windows/bin
          retention-days: 5
  Mac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib git flixel https://github.com/HaxeFlixel/flixel/tree/4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxcpp https://github.com/Sirox228/hxcpp
          haxelib list
          haxelib install refactor
          haxelib run refactor replace source *.hx "/import vlc.MP4Handler;/import hxcodec.VideoHandler;\nimport hxcodec.VideoSprite;/"
          haxelib run refactor replace source *.hx "/MP4Handler/VideoSprite/"
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: mac
          path: export/release/macos/bin
          retention-days: 5
  Windows32:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib git flixel https://github.com/HaxeFlixel/flixel/tree/4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript 
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxcpp https://github.com/Sirox228/hxcpp
          haxelib list
          haxelib install refactor
          haxelib run refactor replace source *.hx "/import vlc.MP4Handler;/import hxcodec.VideoHandler;\nimport hxcodec.VideoSprite;/"
          haxelib run refactor replace source *.hx "/MP4Handler/VideoSprite/"
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}} -32"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windows x32
          path: export/release/windows/bin
          retention-days: 5
  Html5:
     runs-on: windows-latest

     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2.3.0

       - uses: krdlab/setup-haxe@master
         with:
           haxe-version: 4.2.5
       # Runs a set of commands using the runners shell
       - name: Install Haxelib
         run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib git flixel https://github.com/HaxeFlixel/flixel/tree/4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript 
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxcpp https://github.com/Sirox228/hxcpp
          haxelib list
          haxelib install refactor
          haxelib run refactor replace source *.hx "/import vlc.MP4Handler;/import hxcodec.VideoHandler;\nimport hxcodec.VideoSprite;/"
          haxelib run refactor replace source *.hx "/MP4Handler/VideoSprite/"
         shell: cmd
       - name: Create Version Tag
         run: echo "${{github.run_id}}" > VERSION
       - name: Compile
         run: haxelib run lime build html5 --app-version="4.0.0-${{ github.run_id}}"
       - name: Publish Artifact
         uses: actions/upload-artifact@v2.2.4
         with:
           name: html5
           path: export/release/html5/bin
           retention-days: 5
